Lunch/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lunch.Models
{
    public class Menu
    {
        public int  Id  { get; set; }
        public  virtual Food FirstChoice { get; set; }
      //  public int FirstChoiceId { get; set; }
        public virtual Food SecondChoice { get; set;}
        public virtual int FirstChoiceId { get; set; }
        public virtual int SecondChoiceId { get; set; }
                                           //   public int SecondChoiceId { get; set; }
        public DateTime Date { get; set; }

    }
    public class AddMenuViewModel
    {
        [Required]
        [Display(Name="First Meal")]
        public virtual int FirstChoiceId { get; set; }
        [Required]
        [Display(Name ="Second Meal")]
        public virtual int SecondChoiceId { get; set; }

    }
}

Lunch/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lunch.Models;
using Microsoft.AspNet.Identity;
using System.Collections;

namespace Lunch.Controllers
{
    [Authorize]
    public class BookingsController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();
        private Menu CurrentMenu;
        // GET: Bookings
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var booking = db.Booking
                .Where(bookings => bookings.Date.Day == DateTime.Now.Day)
                .Include(b => b.FoodChoice);
            return View(booking.ToList());
        }
        public ActionResult Mybookings()
        {
            var userIdInSession = User.Identity.GetUserId();
            ApplicationUser UserInSession = db.Users.Where(user => user.Id == userIdInSession).First();
            var booking = db.Booking
                .Where(mybooking => mybooking.User.Id == UserInSession.Id)
                .Include(b => b.FoodChoice).ToList();
            return View(booking.ToList());
        }

        [Authorize(Roles ="admin")]
        public ActionResult BookingHistory()
        {
            var booking = db.Booking
                .Include(b => b.FoodChoice);
            return View(booking.ToList());
        }
        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Booking.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create()
        {
            CurrentMenu = db.Menu.Include(m => m.FirstChoice).Include(m => m.SecondChoice).ToList().Last();
            IList MenuFoodList;
            //15 Minute logic
            if (CurrentMenu.Date.Minute + 15 >= DateTime.Now.Minute)
            {
                MenuFoodList = new List<Food>() { CurrentMenu.FirstChoice, CurrentMenu.SecondChoice };
                ViewBag.FoodChoiceId = new SelectList(MenuFoodList, "Id", "Name");
                ViewBag.Status = "intime";
            }
            else
            {
                MenuFoodList = new List<Food>();
                ViewBag.FoodChoiceId = new SelectList(MenuFoodList, "Id", "Name");
                ViewBag.Status = "Menu has not been set, check back later";
            }
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FoodChoiceId,DeliveryLocation,CustomMessage")] AddBookingViewModel booking)
        {
            var userIdInSession = User.Identity.GetUserId();
            ApplicationUser UserInSession = db.Users.Where(user => user.Id == userIdInSession).First();
            Booking bookings = new Booking();
            bookings.Date = DateTime.Now;
            bookings.FoodChoiceId = booking.FoodChoiceId;
            bookings.DeliveryLocation = booking.DeliveryLocation;
            bookings.CustomMessage = booking.CustomMessage;
            bookings.User = UserInSession;

            if (ModelState.IsValid)
            {
                db.Booking.Add(bookings);
                db.SaveChanges();
                return RedirectToAction("Mybookings");
            }

            CurrentMenu = db.Menu.Include(m => m.FirstChoice).Include(m => m.SecondChoice).ToList().Last();
            List<Food> MenuFoodList = new List<Food>() { CurrentMenu.FirstChoice, CurrentMenu.SecondChoice };
            ViewBag.FoodChoiceId = new SelectList(MenuFoodList, "Id", "Name");
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Booking.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.FoodChoiceId = new SelectList(db.Food, "Id", "Name", booking.FoodChoiceId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FoodChoiceId,Date,DeliveryLocation,CustomMessage")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FoodChoiceId = new SelectList(db.Food, "Id", "Name", booking.FoodChoiceId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Booking.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Booking.Find(id);
            db.Booking.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lunch/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lunch.Models;
using Microsoft.AspNet.Identity;
using System.Web.Security;

namespace Lunch.Controllers
{
    public class MenusController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Menu CurrentMenu;

        // GET: Menus
        [Authorize(Roles ="admin")]
        public ActionResult Index()
        {
            var menu = db.Menu.Include(m => m.FirstChoice).Include(m => m.SecondChoice);
            return View(menu.ToList());
        }
        public ActionResult ShowMenu()
        {
            CurrentMenu = db.Menu.Include(m => m.FirstChoice).Include(m => m.SecondChoice).ToList().Last();
            ViewBag.MenuStatus = "Our Menu for the day";
            if (CurrentMenu.Date.Day < DateTime.Now.Day)
            {
                CurrentMenu = null; 
                ViewBag.MenuStatus = "Menu has not been set for day, please check back";
            }
         //   var adminId = db.Roles.First().Users.Where(id => id.UserId == User.Identity.GetUserId()).First().UserI
           return View(CurrentMenu);
        }

        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        
        // GET: Menus/Create
        [Authorize(Roles ="admin")]
        public ActionResult Create()
        {
            ViewBag.FirstChoiceId = new SelectList(db.Food, "Id", "Name");
            ViewBag.SecondChoiceId = new SelectList(db.Food, "Id", "Name");
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstChoiceId,SecondChoiceId")] AddMenuViewModel menu)
        {
            Menu menus = new Menu();
            menus.FirstChoiceId = menu.FirstChoiceId;
            menus.SecondChoiceId = menu.SecondChoiceId;
            menus.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Menu.Add(menus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FirstChoiceId = new SelectList(db.Food, "Id", "Name", menu.FirstChoiceId);
            ViewBag.SecondChoiceId = new SelectList(db.Food, "Id", "Name", menu.SecondChoiceId);
            return View(menu);
        }

        // GET: Menus/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            ViewBag.FirstChoiceId = new SelectList(db.Food, "Id", "Name", menu.FirstChoiceId);
            ViewBag.SecondChoiceId = new SelectList(db.Food, "Id", "Name", menu.SecondChoiceId);
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstChoiceId,SecondChoiceId")] Menu menu)
        {
            menu.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FirstChoiceId = new SelectList(db.Food, "Id", "Name", menu.FirstChoiceId);
            ViewBag.SecondChoiceId = new SelectList(db.Food, "Id", "Name", menu.SecondChoiceId);
            return View(menu);
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menu.Find(id);
            db.Menu.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lunch/Views/Menus/Create.cshtml
@model Lunch.Models.AddMenuViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Menu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstChoiceId, "FirstChoiceId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FirstChoiceId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FirstChoiceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondChoiceId, "SecondChoiceId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SecondChoiceId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SecondChoiceId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Menu Catalogue", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lunch/Views/Menus/Delete.cshtml
@model Lunch.Models.Menu

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstChoice.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstChoice.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondChoice.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondChoice.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lunch/Views/Menus/Details.cshtml
@model Lunch.Models.Menu

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstChoice.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstChoice.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondChoice.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondChoice.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lunch/Views/Menus/Edit.cshtml
@model Lunch.Models.Menu

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Menu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstChoiceId, "FirstChoiceId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FirstChoiceId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FirstChoiceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondChoiceId, "SecondChoiceId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SecondChoiceId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SecondChoiceId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Menu Catalogue", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lunch/Views/Menus/Index.cshtml
@model IEnumerable<Lunch.Models.Menu>

@{
    ViewBag.Title = "Menu";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Add Menu", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstChoice.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecondChoice.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstChoice.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SecondChoice.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        @if (item.Date.Day < DateTime.Now.Day)
        {
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.Id })
        </td>

        }
        else
        {
            <td>
                @Html.ActionLink("Book", "Create", "Bookings")|
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        }
    </tr>
}

</table>

Lunch/Views/Menus/ShowMenu.cshtml
@model Lunch.Models.Menu

@{
    ViewBag.Title = "ShowMenu";
}

<h2>ShowMenu</h2>

<div>
    <h4>Menu</h4>
    <hr />
    @if (Model != null)
    {
     <h4> @ViewBag.MenuStatus</h4>
    <hr />
     <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstChoice.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstChoice.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondChoice.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondChoice.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
    <p>
        @Html.ActionLink("Book", "Create", "Bookings") |
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
    }
    else
    {
        <h4> @ViewBag.MenuStatus</h4>
    }
</div>